version: '2'
services:
  postgres:
    image: postgres:16
    container_name: postgres_fainapp
    environment:
      POSTGRES_DB: fainapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432
    volumes:
      - postgres_fainapp:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis_fainapp
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    

volumes:
  postgres_fainapp:
  redis_data:
