version: '1.0'
services:
  database:
    image: postgres:16
    container_name: postgres_fainapp
    environment:
      POSTGRES_DB: fainapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432
    volumes:
      - postgres_fainapp:/var/lib/postgresql/data

volumes:
  postgres_fainapp: